const header=document.querySelector('header'),menu=document.querySelector('.menu-toggle'),links=document.querySelector('.nav-links'),icon=menu.querySelector('i');
document.querySelectorAll('strong, .footer-column p').forEach(element=>{if(element.textContent.includes('info@astrixit.com'))element.textContent=element.textContent.replace('info@astrixit.com','astrixitsolution@gmail.com')});
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>10));
menu.addEventListener('click',()=>{links.classList.toggle('active');icon.className=links.classList.contains('active')?'fa-solid fa-xmark':'fa-solid fa-bars'});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{links.classList.remove('active');icon.className='fa-solid fa-bars'}));
const form=document.querySelector('#contactForm'),message=document.querySelector('#formMessage');
form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;button.innerHTML='Submitting…';try{const result=await fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(form)).toString()});if(!result.ok)throw Error();form.reset();message.textContent='✓ Request submitted successfully! We will contact you soon.';message.className='success'}catch{message.textContent='Please try again, or contact us on WhatsApp.';message.className='error'}finally{button.disabled=false;button.innerHTML='Submit Request <i class="fa-solid fa-arrow-right"></i>'}});

const serviceDetails={
  'IT Support':{icon:'fa-laptop',intro:'Reliable day-to-day support that keeps your computers, users and operations productive.',items:['Desktop and laptop troubleshooting','Software installation and issue resolution','Hardware diagnosis and replacement guidance','On-site and remote technical assistance']},
  'Networking Solutions':{icon:'fa-network-wired',intro:'A secure, well-planned network built for smooth connectivity across your workplace.',items:['LAN, WiFi and router configuration','Network infrastructure planning and setup','Connectivity troubleshooting and optimisation','Scalable solutions for offices and institutions']},
  'CCTV & Surveillance':{icon:'fa-video',intro:'Professional surveillance systems that help you monitor and protect what matters most.',items:['CCTV installation and camera placement','DVR/NVR configuration and setup','Mobile monitoring configuration','Maintenance and performance checks']},
  'Printer Support':{icon:'fa-print',intro:'Fast printer support to minimise downtime in your office or home workspace.',items:['Printer installation and setup','Paper, ink and connectivity troubleshooting','Repair and maintenance assistance','Network printer configuration']},
  'AMC Services':{icon:'fa-screwdriver-wrench',intro:'Proactive annual maintenance that makes your IT infrastructure dependable all year round.',items:['Scheduled preventive maintenance','Priority support for technical issues','System health and performance checks','Flexible coverage for your IT setup']},
  'Cyber Security':{icon:'fa-shield-halved',intro:'Practical security measures that give your systems and network a stronger first line of defence.',items:['Basic system and network security review','Endpoint protection guidance','Secure configuration recommendations','Security awareness and best-practice support']}
};
const modal=document.createElement('div');
modal.className='service-modal';
modal.innerHTML='<div class="modal-backdrop"></div><section class="modal-panel" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><button class="modal-close" aria-label="Close service details"><i class="fa-solid fa-xmark"></i></button><div class="modal-icon"></div><p class="eyebrow">ASTRIX IT SERVICE</p><h2 id="modalTitle"></h2><p class="modal-intro"></p><h3>What’s included</h3><ul class="modal-list"></ul><a class="primary-btn modal-enquire" href="#contact">Request this service <i class="fa-solid fa-arrow-right"></i></a></section>';
document.body.append(modal);
const closeModal=()=>{modal.classList.remove('open');document.body.classList.remove('modal-open')};
document.querySelectorAll('.service-card').forEach(card=>card.addEventListener('click',event=>{event.preventDefault();const name=card.querySelector('h3').textContent,detail=serviceDetails[name];if(!detail)return;modal.querySelector('.modal-icon').innerHTML=`<i class="fa-solid ${detail.icon}"></i>`;modal.querySelector('#modalTitle').textContent=name;modal.querySelector('.modal-intro').textContent=detail.intro;modal.querySelector('.modal-list').innerHTML=detail.items.map(item=>`<li><i class="fa-solid fa-circle-check"></i>${item}</li>`).join('');modal.classList.add('open');document.body.classList.add('modal-open')}));
modal.querySelector('.modal-close').addEventListener('click',closeModal);modal.querySelector('.modal-backdrop').addEventListener('click',closeModal);modal.querySelector('.modal-enquire').addEventListener('click',closeModal);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});
